### ISSUE TITLE
[FEATURE] Add transition animation to all hover effects on the website.

### ISSUE THREAD

**Issue by Timonwa** [Timonwa/techroadmap#79]
**Is your feature request related to a problem? Please describe.**
When you hover over any of the links on the website, there is no transition from one colour to the other.

**Describe the solution you'd like**
I would like for them to have a nice transition from one colour to another when a user hovers over any of the links.

## Links by categories:
- [x] the Nav links
- [x] the links in the Footer
- [x] the links in the Open Source Section found on all the pages
- [x] the cards in the Careers in Tech Section found on the home and careers page
- [x] the resource links found in all the sections
- [x] the pink links in the paragraphs

Example:
```css
a {
  color: white;
  transition: color 500ms ease-in-out;
  }

a:hover {
  color: grey;
  }
```
Find links to resources on **CSS animations** here: https://www.techroadmap.xyz/careers/frontend#css-advanced
